part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const home = _Paths.home;
  static const login = _Paths.login;
  static const register = _Paths.register;
  static const wargaDashboard = _Paths.wargaDashboard;
  static const wargaPenerimaan = _Paths.wargaPenerimaan;
  static const wargaPengaduan = _Paths.wargaPengaduan;
  static const petugasVerifikasiDashboard = _Paths.petugasVerifikasiDashboard;
  static const petugasDesaDashboard = _Paths.petugasDesaDashboard;
  static const donaturDashboard = _Paths.donaturDashboard;
  static const splash = _Paths.splash;
  static const permintaanPenjadwalan = _Paths.permintaanPenjadwalan;
  static const daftarPenerima = _Paths.daftarPenerima;
  static const detailPenerima = _Paths.detailPenerima;
  static const konfirmasiPenerima = _Paths.konfirmasiPenerima;
  static const pelaksanaanPenyaluran = _Paths.pelaksanaanPenyaluran;
  static const profile = _Paths.profile;
  static const riwayatPenitipan = _Paths.riwayatPenitipan;
  static const daftarDonatur = _Paths.daftarDonatur;
  static const detailDonatur = _Paths.detailDonatur;
  static const tambahPenyaluran = _Paths.tambahPenyaluran;
  static const daftarPenerimaPenyaluran = _Paths.daftarPenerimaPenyaluran;
  static const detailPenerimaPenyaluran = _Paths.detailPenerimaPenyaluran;
  static const laporanPenyaluran = _Paths.laporanPenyaluran;
  static const detailPenyaluran = _Paths.detailPenyaluran;
  static const riwayatPenyaluran = _Paths.riwayatPenyaluran;
  static const wargaDetailPenerimaan = _Paths.wargaDetailPenerimaan;
  static const detailPengaduan = _Paths.detailPengaduan;
  static const wargaDetailPengaduan = _Paths.wargaDetailPengaduan;
  static const riwayatPengaduan = _Paths.riwayatPengaduan;
  static const qrScanner = _Paths.qrScanner;
  static const konfirmasiPenerimaQr = _Paths.konfirmasiPenerimaQr;
  static const PENGADUAN = '/pengaduan';
  static const TAMBAH_PENGADUAN = '/tambah-pengaduan';
  static const PENGADUAN_DETAIL = '/pengaduan-detail';
  static const PROFILE = '/profile';
  static const NOTIFIKASI = '/notifikasi';
}

abstract class _Paths {
  _Paths._();
  static const home = '/home';
  static const login = '/login';
  static const register = '/register';
  static const wargaDashboard = '/warga-dashboard';
  static const wargaPenerimaan = '/warga-penerimaan';
  static const wargaPengaduan = '/warga-pengaduan';
  static const petugasVerifikasiDashboard = '/petugas-verifikasi-dashboard';
  static const petugasDesaDashboard = '/petugas-desa-dashboard';
  static const donaturDashboard = '/donatur-dashboard';
  static const splash = '/splash';
  static const permintaanPenjadwalan = '/permintaan-penjadwalan';
  static const daftarPenerima = '/daftar-penerima';
  static const detailPenerima = '/daftar-penerima/detail';
  static const konfirmasiPenerima = '/daftar-penerima/konfirmasi';
  static const pelaksanaanPenyaluran = '/pelaksanaan-penyaluran';
  static const profile = '/profile';
  static const riwayatPenitipan = '/petugas-desa/riwayat-penitipan';
  static const daftarDonatur = '/daftar-donatur';
  static const detailDonatur = '/daftar-donatur/detail';
  static const tambahPenyaluran = '/tambah-penyaluran';
  static const daftarPenerimaPenyaluran = '/daftar-penerima-penyaluran';
  static const detailPenerimaPenyaluran = '/detail-penerima-penyaluran';
  static const laporanPenyaluran = '/laporan-penyaluran';
  static const detailPenyaluran = '/detail-penyaluran';
  static const riwayatPenyaluran = '/petugas-desa/riwayat-penyaluran';
  static const wargaDetailPenerimaan = '/warga/detail-penerimaan';
  static const detailPengaduan = '/detail-pengaduan';
  static const wargaDetailPengaduan = '/warga/detail-pengaduan';
  static const riwayatPengaduan = '/petugas-desa/riwayat-pengaduan';
  static const qrScanner = '/petugas-desa/qr-scanner';
  static const konfirmasiPenerimaQr = '/petugas-desa/konfirmasi-penerima/:id';
  static const PENGADUAN = '/pengaduan';
  static const TAMBAH_PENGADUAN = '/tambah-pengaduan';
  static const PENGADUAN_DETAIL = '/pengaduan-detail';
  static const PROFILE = '/profile';
  static const NOTIFIKASI = '/notifikasi';
}
